# Generated by Django 3.0 on 2019-12-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsdbApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowongan',
            name='gaji',
        ),
        migrations.AddField(
            model_name='lowongan',
            name='gaji_max',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='gaji_min',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='pengalaman',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='deskripsi',
            field=models.TextField(max_length=10000),
        ),
    ]
