# Generated by Django 3.0 on 2019-12-13 04:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsdbApp', '0002_auto_20191212_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='isi',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
